version: '3.5'

services:

  zookeeper:
    image: quay.io/strimzi/kafka:0.30.0-kafka-3.2.0
    command: [
        "sh", "-c",
        "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - 12181:2181
    environment:
      LOG_DIR: /tmp/logs
    networks:
      - battery-network

  kafka:
    image: quay.io/strimzi/kafka:0.30.0-kafka-3.2.0
    command: [
        "sh", "-c",
        "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - 19092:9092
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_HOST_NAME: kafka #Change the ip to your machine IP, when run locally
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 #Change the ip to your machine IP, when run locally
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - battery-network

  mariadb:
    image: mariadb:10.9.2
    restart: on-failure
    environment:
      MARIADB_USER: psaUser
      MARIADB_PASSWORD: p5aus3R!
      MARIADB_ROOT_PASSWORD: rootx
      MARIADB_DATABASE: psa_db
    ports:
      - 13306:3306
    volumes:
      - ./mariadb-data:/var/lib/mysql
    networks:
      - battery-network

  psa-api:
    image: 325224159075.dkr.ecr.us-east-1.amazonaws.com/power-sources-aggregator:latest
      #image: 325224159075.dkr.ecr.us-east-1.amazonaws.com/power-sources-aggregator:native
    ports:
      - 15000:5000
    restart: on-failure
    depends_on:
      - kafka
      - mariadb
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - battery-network

networks:
  battery-network:
    name: batnet
